name: Lint, Typecheck, and Format

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma types
        run: npm -w server run build

      - name: Run lint
        run: npm run lint

      - name: Run format check
        run: npm run format -- --check

      - name: Run typecheck
        run: npm run typecheck

env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/larpcal
